#!/usr/bin/env bash
set -eu

{
  docker run --rm --name mongo --network vnet -d mongo

  docker build . -t simple-chat:local \
  && docker run --rm --name simple-chat --network vnet \
  -p 3000:3000 -it simple-chat:local

  docker stop mongo
}
