#!/usr/bin/env bash
set -eu

{
  mongo() {
    docker run --rm --name mongo --network vnet -i mongo
  }
  mongo &

  docker build . -t simple-chat:local \
  && docker run --rm --name simple-chat --network vnet \
  -p 3000:3000 -it simple-chat:local
}
